package Catalogo::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Catalogo::DBSchema',
    connect_info => 'dbi:Pg:dbname=catalogo;host=127.0.0.1'
);

=head1 NAME

Catalogo::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Catalogo>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Catalogo::DBSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

Daniel Ruoso

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
